#!/usr/bin/env bash
# install.sh - Install docker-backup to the system
set -euo pipefail

INSTALL_DIR="/opt/docker-backup"
SYSTEMD_DIR="/etc/systemd/system"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BOLD='\033[1m'
NC='\033[0m'

info()  { echo -e "${GREEN}[+]${NC} $*"; }
warn()  { echo -e "${YELLOW}[!]${NC} $*"; }
error() { echo -e "${RED}[-]${NC} $*"; }
bold()  { echo -e "${BOLD}$*${NC}"; }

# --- Check root ---
if [[ $EUID -ne 0 ]]; then
    error "This script must be run as root"
    exit 1
fi

bold "=== Docker Backup Installer ==="
echo ""

# --- Check dependencies ---
info "Checking dependencies..."
missing=()
for cmd in age zstd rsync docker jq curl ssh tar; do
    if ! command -v "$cmd" &>/dev/null; then
        missing+=("$cmd")
    fi
done

if [[ ${#missing[@]} -gt 0 ]]; then
    error "Missing dependencies: ${missing[*]}"
    echo "  Install them with your package manager, e.g.:"
    echo "    pacman -S ${missing[*]}"
    exit 1
fi
info "All dependencies found"

# --- Generate age keypair if needed ---
AGE_DIR="/root/.age"
AGE_KEY_FILE="$AGE_DIR/backup.key"

if [[ ! -f "$AGE_KEY_FILE" ]]; then
    info "Generating age keypair..."
    mkdir -p "$AGE_DIR"
    chmod 700 "$AGE_DIR"
    age-keygen -o "$AGE_KEY_FILE" 2>/tmp/age_keygen_out
    chmod 600 "$AGE_KEY_FILE"

    AGE_PUBLIC_KEY="$(grep '^# public key:' /tmp/age_keygen_out | sed 's/# public key: //')"
    if [[ -z "$AGE_PUBLIC_KEY" ]]; then
        AGE_PUBLIC_KEY="$(grep '^# public key:' "$AGE_KEY_FILE" | sed 's/# public key: //')"
    fi
    rm -f /tmp/age_keygen_out

    info "Age private key: $AGE_KEY_FILE"
    bold "Age public key:  $AGE_PUBLIC_KEY"
    echo ""
    warn "IMPORTANT: Back up $AGE_KEY_FILE securely! Without it, backups cannot be decrypted."
    echo ""
else
    info "Age keypair already exists: $AGE_KEY_FILE"
    AGE_PUBLIC_KEY="$(grep '^# public key:' "$AGE_KEY_FILE" | sed 's/# public key: //')"
fi

# --- Generate SSH key for backups ---
SSH_KEY="/root/.ssh/backup_ed25519"

if [[ ! -f "$SSH_KEY" ]]; then
    info "Generating SSH key for backups..."
    ssh-keygen -t ed25519 -f "$SSH_KEY" -N "" -C "docker-backup@$(hostname)" >/dev/null 2>&1
    chmod 600 "$SSH_KEY"
    info "SSH key generated: $SSH_KEY"
    echo ""
    bold "Add this public key to the remote server's ~/.ssh/authorized_keys:"
    echo ""
    cat "${SSH_KEY}.pub"
    echo ""
else
    info "SSH key already exists: $SSH_KEY"
fi

# --- Collect configuration ---
echo ""
bold "=== Configuration ==="
echo ""

CONFIG_FILE="$INSTALL_DIR/docker-backup.conf"

if [[ -f "$CONFIG_FILE" ]]; then
    warn "Existing config found: $CONFIG_FILE"
    read -rp "Overwrite? [y/N] " overwrite
    if [[ ! "$overwrite" =~ ^[Yy] ]]; then
        info "Keeping existing config"
        SKIP_CONFIG=true
    else
        SKIP_CONFIG=false
    fi
else
    SKIP_CONFIG=false
fi

if [[ "$SKIP_CONFIG" == "false" ]]; then
    read -rp "Docker source directory [/opt/docker]: " src_dir
    src_dir="${src_dir:-/opt/docker}"

    read -rp "Remote backup host: " remote_host
    read -rp "Remote backup user [backup]: " remote_user
    remote_user="${remote_user:-backup}"
    read -rp "Remote SSH port [22]: " remote_port
    remote_port="${remote_port:-22}"
    read -rp "Remote backup path [/backups/$(hostname)]: " remote_path
    remote_path="${remote_path:-/backups/$(hostname)}"

    read -rp "Webhook URL (leave empty to skip): " webhook_url
    webhook_type="discord"
    telegram_chat_id=""
    if [[ -n "$webhook_url" ]]; then
        read -rp "Webhook type [discord/slack/telegram]: " webhook_type
        webhook_type="${webhook_type:-discord}"
        if [[ "$webhook_type" == "telegram" ]]; then
            echo "  For Telegram, WEBHOOK_URL should be your bot token."
            read -rp "Telegram chat ID: " telegram_chat_id
        fi
    fi

    # Write config
    mkdir -p "$INSTALL_DIR"
    cat > "$CONFIG_FILE" <<CONF
# docker-backup.conf - Generated by install.sh on $(date)

BACKUP_SOURCE_DIR=$src_dir
BACKUP_LOCAL_STAGING=/var/tmp/backups

REMOTE_HOST=$remote_host
REMOTE_USER=$remote_user
REMOTE_PORT=$remote_port
REMOTE_PATH=$remote_path
SSH_KEY=$SSH_KEY

AGE_RECIPIENT=$AGE_PUBLIC_KEY
AGE_KEY_FILE=$AGE_KEY_FILE

WEBHOOK_URL=$webhook_url
WEBHOOK_TYPE=$webhook_type
TELEGRAM_CHAT_ID=$telegram_chat_id

RETAIN_DAILY=7
RETAIN_WEEKLY=4
RETAIN_MONTHLY=3
COMPRESSION_LEVEL=3
CONF

    chmod 600 "$CONFIG_FILE"
    info "Config written: $CONFIG_FILE"
fi

# --- Install files ---
echo ""
info "Installing to $INSTALL_DIR..."
mkdir -p "$INSTALL_DIR/lib"

cp "$SCRIPT_DIR/docker-backup" "$INSTALL_DIR/docker-backup"
chmod 755 "$INSTALL_DIR/docker-backup"

for lib_file in "$SCRIPT_DIR"/lib/*.sh; do
    cp "$lib_file" "$INSTALL_DIR/lib/"
done

info "Scripts installed"

# --- Install systemd units ---
info "Installing systemd units..."
cp "$SCRIPT_DIR/docker-backup.service" "$SYSTEMD_DIR/"
cp "$SCRIPT_DIR/docker-backup.timer" "$SYSTEMD_DIR/"

systemctl daemon-reload
systemctl enable docker-backup.timer
systemctl start docker-backup.timer

info "Timer enabled and started"
echo "  Next trigger: $(systemctl show docker-backup.timer --property=NextElapseUSecRealtime --value 2>/dev/null || echo 'check with systemctl list-timers')"

# --- Done ---
echo ""
bold "=== Installation Complete ==="
echo ""
info "Backup script:  $INSTALL_DIR/docker-backup"
info "Config file:    $CONFIG_FILE"
info "Timer status:   systemctl status docker-backup.timer"
info "Manual run:     systemctl start docker-backup.service"
info "View logs:      journalctl -u docker-backup.service"
echo ""

# --- Offer test run ---
read -rp "Run a dry-run test now? [y/N] " test_run
if [[ "$test_run" =~ ^[Yy] ]]; then
    echo ""
    bold "=== Dry Run ==="
    "$INSTALL_DIR/docker-backup" --dry-run
fi
